#xxl.job.admin.addresses: http://192.168.1.179:8080/xxl-job-admin
#xxl.job.executor.appname: xxl-job-executor-sample
server.port: 8449

test.value: test_${user.name}


spring:
  # ???????
  datasource:
    # ???????
    type: com.zaxxer.hikari.HikariDataSource
    # ????????????
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.173:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: london123
  redis:
    host: 192.168.0.200
    port: 6379
    password: netopstec
    database: 8
  data:
    elasticsearch:
      client:
        rest:
          uris: https://192.168.0.200:9200 # es的连接地址及端口号
          username: elastic
          password: elastic
          connection-timeout: 10000 # 连接超时时间，单位毫秒
          socket-timeout: 30000 # 套接字超时时间，单位毫秒
          max-conn-per-route: 100 # 每个路由的最大连接数
          max-conn-total: 200 # 总的最大连接
          use-ssl: true
mybatis-plus:
  global-config:
    db-config:
      id-type=auto:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
